### ISSUE TITLE
Input Box Suggestion

### ISSUE THREAD

**Issue by US-Ali** [krishKM/Modern-UI-Components-for-VBA#3] opened 2018-07-08 03:04 UTC
First I must say thank you for a beautiful and brilliant job. This is so rich and easy to use. I have a question or suggestion however. Can you include an Input Box that has a combo box  with a drop down instead of just a text box? 

This is very useful when at run-time, you can pass a row-source to it and from the drop down, the user can select any of the drop down option. When passing the row-source, their should be an option to indicate of the RowSourceType = "Value List" or "Table/Query" and if AllowValueListEdits = False/True.

Additional variables for the row-source of the combo box should also include:
ColumnCount 
ColumnWidths and 
BoundColumn

Thank you.

**Comment by krishKM** [comment] 2018-08-03 11:42
Thanks for the suggestion but i think for above needs, MS ACCESS standard combobox would be very suitable. However I'm planning to provide a nice looking ComboBox/DropDown box.

**Comment by US-Ali** [comment] 2018-08-03 21:37
This is appreciated. I am actually using MS Access standard combo box to accomplish this already but your utility has changed the way my Access file looks. The combo box input box seems to be what is missing. I must say that you have done a very wonderful job,

**Comment by krishKM** [comment] 2018-08-08 14:28
DropDownBox added 👍 thank you for the suggestion.

**Comment by US-Ali** [comment] 2018-08-08 16:07
Thank you for giving this your attention as promised.

Everything looks good as usual but I observed that it was requesting for other .dll files meaning that I will need to use not just VBA_TOOLS.dll alone (my preferred option) but download the other files too which is too many for me. 

I was also unable to manage the column widths. If I want to hide the first column (representing the index field) I should set my array to say Array(0, 10) for example, but the first column is still showing and occupying the entire box living no room for me to see the second column.

Lastly, I also noticed that when I set the "boundColumn" to either 0 or 1, the outcome or feedback was still the second column. I don't know if I am doing something wrong. Do explain this better please.

Thanks.

**Comment by krishKM** [comment] 2018-08-08 20:32
Thanks for that. Bugs are corrected now. We also added OnDemand repository loading which will load dlls as per need. You may delete {MySQL, ZintNet, WinSCP, signalR) dlls if you don't require barcode, ftp, services. Other Dlls are pretty much belongs to Microsoft Windows.NET framework they are in the bin folder in case if anyone don't have .net framework >4.5 installed in their machine. You can always check each dll for virus. 
thanks again for your contribution.

**Comment by US-Ali** [comment] 2018-08-10 18:19
I was able to check it out today and it works perfectly - thank you again. One last thing on this (my apologies again), is there a way to control the "List Rows" property? If I have 3 records on the drop down list, I don't want the list row to extend beyond the 3 records except in a situation where I have more than say 16 records and I can decide how many rows to display before showing the scroll bar. Right now what you have displays only the first 6 records without showing the scroll bar even if I have more than 6 records. I will have to use the tab/down key to navigate to the records below the 6th row. Not all users are so smart to know what to do in such situations. It will be appreciated if you can fix this.

**Comment by krishKM** [comment] 2018-08-13 22:40
Scrollbars enabled. I'm currently not happy about how the DropDown look. I will make a new design when I have more time. Check out the context menu function :)

**Comment by US-Ali** [comment] 2018-08-14 00:48
You just made this even more better. I think the MS Access community will forever thank you for this. The drop down menu is working perfectly now except for three things that I observed while testing it which I think needs fixing. 

1. I decided to change the records in the "testTable" to Calendar Months (January to December) in place of the "url" column. This gave me 12 rows and both the horizontal and vertical scrollbars displayed perfectly. However, I noticed that even though I set my column width to 50, most of the rows items were truncated in the drop down. September was displayed as "Sept..." likewise November (as "Nove...") and December (as "Dece..."). I am however surprised that the others displayed perfectly. I increased the column width to 100 and nothing changed.

2. Also, I am not able to select any of the rows by clicking the space in front of any of the row items. I have to click on January for example for it to be selected. If I click on right side of the row containing any of the months, it doesn't select. But overall, well done for a job well done.

3. Lastly and this goes for **all the input boxes** - kindly make the title of the buttons to be optional instead of having "Done" as the only available caption. I might want to use "**Continue**", "**Process**", "**Run**", etc rather than just "**Done**' which might not be suitable for every occasion.

**Comment by krishKM** [comment] 2018-08-15 09:30
Point 3 is done. you can now pass `doneButtonCaption` parameter like this `doneButtonCaption:="Proceed"`.


Can assist how I can reproduce 1, 2? I.e. what is your dataSource and data and perhaps your code to produce the dropDown.

thanks

**Comment by krishKM** [comment] 2018-08-15 15:14
Thank you for the pictures.

*Point 2*: Fixed.

*Point 1*: Also kind of fixed by fixing point 2. Besides, you don't need to provide column withs for all columns unless you want to hide them. That's because by default each column will grow horizontally to it's content length.
`
array(0) 'will hide the first column. Rest of the columns will grow to their content widths.
`

**Closed** 2018-08-20 19:55 UTC
