### ISSUE TITLE
ShowdialogRich issue

### ISSUE THREAD

**Issue by lajjutz** [krishKM/Modern-UI-Components-for-VBA#19] opened 2018-11-25 19:49 UTC
Hello

First at all, thanks for your work,it is simply great..

I was checking the showdialogrich function, but looks like something is missing, I executed from sample dll_test.accdb.
![image](https://user-images.githubusercontent.com/44538069/48983749-655c5a00-f0b8-11e8-92bd-c8ed0443b69c.png)
"Cannot load the specific file Newtonsoft.Json.... System cannot find the specific file"

Other functions and adds are working well, but I don't know why specifically this one is not. Do you know what can be?.

Thanks in advance

**Comment by krishKM** [comment] 2018-11-26 10:01
Good Morning, have you downloaded the bin folder and placed where your project file is? 
here is the [bin folder](https://github.com/krishKM/Modern-UI-Components-for-VBA/tree/master/samples)

the bin folder has all the necessary files included. please tell me if this has worked. thx

**Comment by lajjutz** [comment] 2018-11-26 15:11
Sure..! bin folder is ok..

![image](https://user-images.githubusercontent.com/44538069/49022626-e8ce8780-f15a-11e8-9638-ab3b09a437a1.png)

Like I told the other functions are working fine, the issue only happends in RichDialog samples:

![image](https://user-images.githubusercontent.com/44538069/49022706-1f0c0700-f15b-11e8-9138-5f42f8c11f3e.png)

Thanks again for your answer and support

**Comment by krishKM** [comment] 2018-11-26 15:17
have released an update removing the JSon bindings. please try to download the vba_tools.dll and the bin folder. please let me know if this has worked

**Comment by lajjutz** [comment] 2018-11-26 19:13
Thanks again for your fast response..

I downloaded the new files and I replaced them all, but look like still there are issues:

![image](https://user-images.githubusercontent.com/44538069/49036214-b766b380-f17c-11e8-93fc-82a1c899aed5.png)

![image](https://user-images.githubusercontent.com/44538069/49036227-c9e0ed00-f17c-11e8-9862-6a81edfef157.png)

Hope you can figure out what it is..

**Comment by krishKM** [comment] 2018-11-26 20:12
Please download the bin folder and vba_tools.dll again and try. I've made some changes.

**Comment by lajjutz** [comment] 2018-11-26 21:03
Downloaded..:

![image](https://user-images.githubusercontent.com/44538069/49041900-24357a00-f18c-11e8-9868-69acf2520d92.png)

![image](https://user-images.githubusercontent.com/44538069/49041954-55ae4580-f18c-11e8-8cb0-addcfc12a211.png)

Same result..,

**Comment by krishKM** [comment] 2018-11-26 21:05
¯\_(⊙︿⊙)_/¯
Are you operating on windows 7? Can you tell me what version of office you've installed?

**Comment by lajjutz** [comment] 2018-11-26 21:09
Yes..

![image](https://user-images.githubusercontent.com/44538069/49042165-f3a21000-f18c-11e8-96bb-a60ffa0d130d.png)

![image](https://user-images.githubusercontent.com/44538069/49042187-07e60d00-f18d-11e8-84a6-d0f165c76ca7.png)

Don't worry my friend, as I told you, the rest of the functions are working very well, let's suppose is something to do with my software versions..

**Comment by krishKM** [comment] 2018-11-26 21:17
thanks i'm installing win7 to debug this. I will post once i have a result

**Comment by lajjutz** [comment] 2018-11-26 21:39
Yes..

![image](https://user-images.githubusercontent.com/44538069/49043517-f3a40f00-f190-11e8-81f1-189fc8a412a6.png)

![image](https://user-images.githubusercontent.com/44538069/49043680-63b29500-f191-11e8-8273-6d45b6ec428b.png)

Regards

**Comment by krishKM** [comment] 2018-11-27 00:32
I have just installed a fresh Win7 vm and  had similar error messages. I could not install .NET 4.7.2 but i did install 4.5 using this [Microsoft link](https://download.microsoft.com/download/B/A/4/BA4A7E71-2906-4B2D-A0E1-80CF16844F5F/dotNetFx45_Full_setup.exe)

After that i could use the sample accdb without any issues. I thought newer .net frameworks always be backwards compatible but i can't figure out why this isn't the case with 4.7.2. 

I have made some changes in the config file. download the latest vba_tools.dll and see if it works, if not try installing the .net framework 4.5 and see if that fixes the issue. ( you might have to uninstall 4.7.2 and then install it again after installing 4.5)

**Comment by lajjutz** [comment] 2018-11-27 16:38
I did as well, uninstall 4.7.2, then install 4.5..
I tried sample.accdb, and the same issue happened with showdialog function, then I installed 4.7.2 again and same thing. Somehow there are maybe some kind of conflict that doesn't allow work with this instance.

I'll wait to upgrade my computer to win10, hope this will fix the issue, Anyway your help and support have been great. thanks again..!

**Comment by krishKM** [comment] 2018-11-27 16:45
Thanks for letting me know. Don't upgrade just for this unless you want to be on win 10. I will try to replicate this issue as someone else is also experiencing exact same problem. 
I'm very much interested in finding the cause.

**Comment by krishKM** [comment] 2018-11-27 21:41
After some research i found, sometimes DLLs from online are being blocked from loading dynamically.
[see this post](https://stackoverflow.com/a/21770848/1684486)

Please right click on the Newtonsoft.Json.dll and click properties and click "unbock" to allow this dll to be loaded.  please let me know how this went. I also made some config changes to the vba_tools.dll. Please also get the new dll from the sample folder. thank you for your cooperation.

**Comment by krishKM** [comment] 2018-11-27 23:48
You might need to unblock all Dlls including vba_tools.dll

**Comment by lajjutz** [comment] 2018-11-28 02:31
Ohhh..!! Unblocking all Dlls related did the trick..!, now it is working.

Looks like importing external dlls even for a small project, requires to "unblock" the files due windows security stuff.

Thank you my friend..!!, your support have been nice.

Regards..

**Comment by krishKM** [comment] 2018-11-28 09:17
Glad it worked. I'm closing this ticket.

**Closed by krishKM** 2018-11-28 09:17 UTC
Labels: duplicate
